plugins {
    id("com.android.application")
}

android {
    namespace = "com.w2a.um1c"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.w2a.um1c"
        minSdk = 24
        targetSdk = 34
        versionCode = 127
        versionName = "1.2.7"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
